"""Governed mapping from anonymized city codes to real destination names."""

from __future__ import annotations


CITY_MAPPING: dict[tuple[str, str], str] = {
    ("France", "City_17"): "Paris",
    ("France", "City_23"): "Nice",
    ("France", "City_14"): "Marseille",
    ("France", "City_25"): "Lyon",
    ("France", "City_46"): "Bordeaux",
    ("France", "City_31"): "Cannes",
    ("France", "City_38"): "Strasbourg",
    ("France", "City_9"): "Toulouse",
    ("France", "City_33"): "Montpellier",
    ("France", "City_36"): "Nantes",
    ("France", "City_30"): "Lille",
    ("France", "City_3"): "Annecy",
    ("France", "City_7"): "Avignon",
    ("France", "City_27"): "Biarritz",
    ("France", "City_45"): "Saint-Malo",
    ("France", "City_32"): "Aix-en-Provence",
    ("France", "City_26"): "Colmar",
    ("France", "City_20"): "Reims",
    ("France", "City_49"): "Dijon",
    ("France", "City_19"): "Rouen",
    ("Morocco", "City_5"): "Marrakech",
    ("Morocco", "City_22"): "Casablanca",
    ("Morocco", "City_20"): "Agadir",
    ("Morocco", "City_39"): "Fès",
    ("Morocco", "City_14"): "Tanger",
    ("Morocco", "City_42"): "Rabat",
    ("Morocco", "City_28"): "Essaouira",
    ("Morocco", "City_23"): "Chefchaouen",
    ("Morocco", "City_29"): "Meknès",
    ("Morocco", "City_31"): "Ouarzazate",
    ("Morocco", "City_36"): "Ifrane",
    ("Morocco", "City_21"): "Tetouan",
    ("Morocco", "City_26"): "Dakhla",
    ("Morocco", "City_45"): "El Jadida",
    ("Morocco", "City_10"): "Merzouga",
    ("Morocco", "City_4"): "Oujda",
    ("Morocco", "City_7"): "Asilah",
    ("Morocco", "City_17"): "Al Hoceima",
    ("Morocco", "City_35"): "Taroudant",
    ("Morocco", "City_46"): "Safi",
    ("Spain", "City_32"): "Barcelona",
    ("Spain", "City_10"): "Madrid",
    ("Spain", "City_43"): "Seville",
    ("Spain", "City_41"): "Valencia",
    ("Spain", "City_15"): "Malaga",
    ("Spain", "City_29"): "Granada",
    ("Spain", "City_49"): "Palma de Mallorca",
    ("Spain", "City_3"): "Alicante",
    ("Spain", "City_47"): "Bilbao",
    ("Spain", "City_13"): "Cordoba",
    ("Spain", "City_39"): "Toledo",
    ("Spain", "City_22"): "San Sebastian",
    ("Spain", "City_5"): "Ibiza",
    ("Spain", "City_21"): "Salamanca",
    ("Spain", "City_40"): "Zaragoza",
    ("Spain", "City_26"): "Tenerife",
    ("Spain", "City_16"): "Girona",
    ("Spain", "City_36"): "Santiago de Compostela",
    ("Spain", "City_1"): "Ronda",
    ("Spain", "City_6"): "Cadiz",
    ("Italy", "City_21"): "Rome",
    ("Italy", "City_37"): "Venice",
    ("Italy", "City_41"): "Milan",
    ("Italy", "City_43"): "Florence",
    ("Italy", "City_33"): "Naples",
    ("Italy", "City_29"): "Pisa",
    ("Italy", "City_19"): "Verona",
    ("Italy", "City_32"): "Bologna",
    ("Italy", "City_49"): "Turin",
    ("Italy", "City_14"): "Sorrento",
    ("Italy", "City_50"): "Palermo",
    ("Italy", "City_20"): "Cinque Terre",
    ("Italy", "City_35"): "Siena",
    ("Italy", "City_25"): "Genoa",
    ("Italy", "City_36"): "Catania",
    ("Italy", "City_8"): "Lake Como",
    ("Italy", "City_7"): "Bari",
    ("Italy", "City_44"): "Rimini",
    ("Italy", "City_6"): "Perugia",
    ("Italy", "City_22"): "Matera",
    ("Japan", "City_43"): "Tokyo",
    ("Japan", "City_50"): "Kyoto",
    ("Japan", "City_6"): "Osaka",
    ("Japan", "City_10"): "Nara",
    ("Japan", "City_3"): "Hiroshima",
    ("Japan", "City_26"): "Yokohama",
    ("Japan", "City_28"): "Sapporo",
    ("Japan", "City_12"): "Fukuoka",
    ("Japan", "City_40"): "Nagoya",
    ("Japan", "City_31"): "Kobe",
    ("Japan", "City_45"): "Okinawa",
    ("Japan", "City_48"): "Hakone",
    ("Japan", "City_18"): "Kanazawa",
    ("Japan", "City_9"): "Nikko",
    ("Japan", "City_39"): "Kamakura",
    ("Japan", "City_5"): "Takayama",
    ("Japan", "City_17"): "Mount Fuji",
    ("Japan", "City_19"): "Beppu",
    ("Japan", "City_13"): "Matsumoto",
    ("Japan", "City_16"): "Kumamoto",
    ("Portugal", "City_45"): "Lisbon",
    ("Portugal", "City_38"): "Porto",
    ("Portugal", "City_43"): "Faro",
    ("Portugal", "City_27"): "Sintra",
    ("Portugal", "City_44"): "Albufeira",
    ("Portugal", "City_14"): "Madeira",
    ("Portugal", "City_8"): "Coimbra",
    ("Portugal", "City_6"): "Braga",
    ("Portugal", "City_13"): "Aveiro",
    ("Portugal", "City_23"): "Cascais",
    ("Portugal", "City_21"): "Lagos",
    ("Portugal", "City_29"): "Évora",
    ("Portugal", "City_4"): "Guimarães",
    ("Portugal", "City_42"): "Óbidos",
    ("Portugal", "City_2"): "Funchal",
    ("Portugal", "City_32"): "Setúbal",
    ("Portugal", "City_48"): "Tomar",
    ("Portugal", "City_22"): "Viana do Castelo",
    ("Portugal", "City_18"): "Portimão",
    ("Portugal", "City_16"): "Monsanto",
    ("Germany", "City_5"): "Berlin",
    ("Germany", "City_7"): "Munich",
    ("Germany", "City_26"): "Hamburg",
    ("Germany", "City_24"): "Cologne",
    ("Germany", "City_11"): "Frankfurt",
    ("Germany", "City_46"): "Düsseldorf",
    ("Germany", "City_8"): "Stuttgart",
    ("Germany", "City_49"): "Heidelberg",
    ("Germany", "City_22"): "Dresden",
    ("Germany", "City_28"): "Nuremberg",
    ("Germany", "City_13"): "Leipzig",
    ("Germany", "City_35"): "Bremen",
    ("Germany", "City_40"): "Bonn",
    ("Germany", "City_38"): "Rothenburg ob der Tauber",
    ("Germany", "City_3"): "Freiburg",
    ("Germany", "City_2"): "Potsdam",
    ("Germany", "City_4"): "Trier",
    ("Germany", "City_15"): "Regensburg",
    ("Germany", "City_37"): "Lübeck",
    ("Germany", "City_10"): "Aachen",
    ("USA", "City_46"): "New York",
    ("USA", "City_17"): "Las Vegas",
    ("USA", "City_28"): "Los Angeles",
    ("USA", "City_13"): "Orlando",
    ("USA", "City_2"): "Miami",
    ("USA", "City_31"): "San Francisco",
    ("USA", "City_7"): "Chicago",
    ("USA", "City_15"): "Washington D.C.",
    ("USA", "City_5"): "Boston",
    ("USA", "City_49"): "Honolulu",
    ("USA", "City_12"): "San Diego",
    ("USA", "City_24"): "Seattle",
    ("USA", "City_8"): "New Orleans",
    ("USA", "City_39"): "Nashville",
    ("USA", "City_21"): "Philadelphia",
    ("USA", "City_4"): "Austin",
    ("USA", "City_3"): "Savannah",
    ("USA", "City_14"): "Charleston",
    ("USA", "City_34"): "Santa Fe",
    ("USA", "City_35"): "Portland",
}
